### ISSUE TITLE
Problem with notifications

### ISSUE THREAD

**Issue by blaquans** [etalab/udata-admin#6]
![anomalie](https://cloud.githubusercontent.com/assets/3227753/7515510/ea4d223a-f4c7-11e4-8fa7-da3de6ac5cef.png)

In the backoffice, I have a notification for an "anomaly" but it isn't clickable.

I run Iceweasel/Firefox 31 with Debian 8

**Comment by davidbgk** [comment]
Confirmed with Firefox 37 and OS X.

**Comment by noirbizarre** [comment]
Yep, it's not yet wired but it will be soon.

- connects to #5
- connects to etalab/udata#18

**Comment by blaquans** [comment]
Ok

**Comment by blaquans** [comment]
It works now. Great work ! 

![anomalie](https://cloud.githubusercontent.com/assets/3227753/8126599/3b663cee-10f0-11e5-84ce-629b39cd4afd.png)
